name: Nightly Test run

on:
  workflow_dispatch:  
  schedule:
    - cron:  '0 0 * * *'

jobs:
  integration-tests-sn:
    name: Integration Tests (Jahia-SN)
    runs-on: self-hosted
    strategy:
      fail-fast: false
    timeout-minutes: 45
    steps:
      - uses: jahia/jahia-modules-action/helper@v2
      - uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: '1.29.2'
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - uses: actions/checkout@v3
      - uses: jahia/jahia-modules-action/integration-tests@v2
        with:
          module_id: OSGi-modules-samples
          jahia_image: jahia/jahia-discovery-dev:8-SNAPSHOT
          incident_service: OSGi-modules-samples-JahiaSN          
          timeout_minutes: 20
          tests_manifest: provisioning-manifest-snapshot.yml
          should_use_build_artifacts: false
          should_skip_artifacts: true
          should_skip_notifications: false
          should_skip_testrail: false
          should_skip_zencrepes: false
          github_artifact_name: osgi-sample-jahia-sn-${{ github.run_number }}
          jahia_artifact_name: osgi-sample-jahia-sn-${{ github.run_number }}          
          bastion_ssh_private_key: ${{ secrets.BASTION_SSH_PRIVATE_KEY_JAHIACI }}
          jahia_license: ${{ secrets.JAHIA_LICENSE_8X_FULL }}
          docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          testrail_username: ${{ secrets.TESTRAIL_USERNAME }}
          testrail_password: ${{ secrets.TESTRAIL_PASSWORD }}
          tests_report_name: Test report (Standalone)
          incident_pagerduty_api_key: ${{ secrets.INCIDENT_PAGERDUTY_API_KEY }}
          incident_pagerduty_reporter_email: ${{ secrets.INCIDENT_PAGERDUTY_REPORTER_EMAIL }}
          incident_pagerduty_reporter_id: ${{ secrets.INCIDENT_PAGERDUTY_REPORTER_ID }}
          incident_google_spreadsheet_id: ${{ secrets.INCIDENT_GOOGLE_SPREADSHEET_ID }}
          incident_google_client_email: ${{ secrets.INCIDENT_GOOGLE_CLIENT_EMAIL }}
          incident_google_api_key_base64: ${{ secrets.INCIDENT_GOOGLE_PRIVATE_KEY_BASE64 }}
          zencrepes_secret: ${{ secrets.ZENCREPES_WEBHOOK_SECRET }}
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report (Standalone)
          path: tests/artifacts/results/xml_reports/*.xml
          reporter: java-junit
          fail-on-error: 'false'

  integration-tests-rl:
    name: Integration Tests (Jahia-RL)
    runs-on: self-hosted
    strategy:
      fail-fast: false
    timeout-minutes: 45
    steps:
      - uses: jahia/jahia-modules-action/helper@v2
      - uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: '1.29.2'
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - uses: actions/checkout@v3
      - uses: jahia/jahia-modules-action/integration-tests@v2
        with:
          module_id: OSGi-modules-samples
          jahia_image: jahia/jahia-discovery:8
          incident_service: OSGi-modules-samples-JahiaRL        
          timeout_minutes: 20
          tests_manifest: provisioning-manifest-snapshot.yml
          should_use_build_artifacts: false
          should_skip_artifacts: true
          should_skip_notifications: false
          should_skip_testrail: false
          should_skip_zencrepes: false
          github_artifact_name: osgi-sample-jahia-rl-${{ github.run_number }}
          jahia_artifact_name: osgi-sample-jahia-rl-${{ github.run_number }}   
          bastion_ssh_private_key: ${{ secrets.BASTION_SSH_PRIVATE_KEY_JAHIACI }}
          jahia_license: ${{ secrets.JAHIA_LICENSE_8X_FULL }}
          docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          testrail_username: ${{ secrets.TESTRAIL_USERNAME }}
          testrail_password: ${{ secrets.TESTRAIL_PASSWORD }}
          tests_report_name: Test report (Standalone)
          incident_pagerduty_api_key: ${{ secrets.INCIDENT_PAGERDUTY_API_KEY }}
          incident_pagerduty_reporter_email: ${{ secrets.INCIDENT_PAGERDUTY_REPORTER_EMAIL }}
          incident_pagerduty_reporter_id: ${{ secrets.INCIDENT_PAGERDUTY_REPORTER_ID }}
          incident_google_spreadsheet_id: ${{ secrets.INCIDENT_GOOGLE_SPREADSHEET_ID }}
          incident_google_client_email: ${{ secrets.INCIDENT_GOOGLE_CLIENT_EMAIL }}
          incident_google_api_key_base64: ${{ secrets.INCIDENT_GOOGLE_PRIVATE_KEY_BASE64 }}
          zencrepes_secret: ${{ secrets.ZENCREPES_WEBHOOK_SECRET }}
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report (Standalone)
          path: tests/artifacts/results/xml_reports/*.xml
          reporter: java-junit
          fail-on-error: 'false'